import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Link from "next/link";
import { Arrow } from "@/components/icons";
import { Breadcrumbs, CTA, Eyebrow } from "@/components/sections";
import { business, services } from "@/data/site";
export function generateStaticParams(){ return services.map(s => ({slug:s.slug})) }
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{ const {slug}=await params; const s=services.find(x=>x.slug===slug); return s ? {title:`${s.title} Melbourne`,description:s.short,alternates:{canonical:`/services/${s.slug}`}}:{} }
export default async function ServicePage({params}:{params:Promise<{slug:string}>}){ const {slug}=await params; const s=services.find(x=>x.slug===slug); if(!s) notFound(); const related=services.filter(x=>x.slug!==s.slug).slice(0,3); const schema={"@context":"https://schema.org","@type":"Service","@id":`${business.url}/services/${s.slug}/#service`,name:s.title,description:s.answer,provider:{"@id":`${business.url}/#organisation`},areaServed:["Melbourne","Victoria"],mainEntityOfPage:`${business.url}/services/${s.slug}`}; const faq={"@context":"https://schema.org","@type":"FAQPage",mainEntity:s.faqs.map(x=>({"@type":"Question",name:x.q,acceptedAnswer:{"@type":"Answer",text:x.a}}))}; return <>
  <section className="service-hero"><div className="shell"><Breadcrumbs items={[{label:"Home",href:"/"},{label:"Services",href:"/services"},{label:s.title}]}/><div className="service-hero-grid"><div><Eyebrow>Essential safety measures</Eyebrow><h1>{s.title}</h1><p>{s.answer}</p><Link className="button" href="/get-a-quote">Discuss your building <Arrow/></Link></div><aside><span>Service scope</span><ul>{s.who.map(x=><li key={x}>{x}</li>)}</ul></aside></div></div></section>
  <section className="section shell detail-grid"><div className="article"><Eyebrow>Regulatory context</Eyebrow><h2>What the requirement is based on</h2><p>{s.basis}</p><div className="notice"><strong>Important</strong><p>Requirements depend on the building’s approved documents and circumstances. This page is general information, not a substitute for building-specific advice.</p></div><Eyebrow>Our process</Eyebrow><h2>A clear path from records to action.</h2><ol className="process-list">{s.steps.map((x,i)=><li key={x}><span>{String(i+1).padStart(2,"0")}</span><p>{x}</p></li>)}</ol></div><aside className="side-contact"><p>Need clarity on the right scope?</p><a href={business.phoneHref}>{business.phone}</a><Link href="/get-a-quote">Request a quote <Arrow/></Link></aside></section>
  <section className="faq-section"><div className="shell"><Eyebrow>Common questions</Eyebrow><h2>What building teams ask us.</h2><div className="faq-list">{s.faqs.map(x=><details key={x.q}><summary>{x.q}<span>+</span></summary><p>{x.a}</p></details>)}</div></div></section>
  <section className="section shell"><Eyebrow>Related services</Eyebrow><div className="related-grid">{related.map(x=><Link key={x.slug} href={`/services/${x.slug}`}><h3>{x.title}</h3><span>Explore <Arrow/></span></Link>)}</div></section><CTA/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faq)}}/>
  </> }
